### ISSUE TITLE
pass click event to component

### ISSUE THREAD

**Issue by indeyets** [hadeeb/react-lazy-hydrate#10]
Is it possible to forward event further down to component In case when `on="click"` option is used? It would make hydration of interactive components so much more usable.

It is mostly important for mobile, as we have "mouseenter" on desktop which, probably, would fire before user has time to click. On mobile, "cilck" (or "tap") would often be the first event page ever gets and we can't waste it

Expected behaviour:
1. user clicks
2. component is hydrated
3. component handles "click" event

**Comment by hadeeb** [comment]
Interesting. If you have any idea how to implement it without too much complexity, we can look into it.

opinion: If your component is interactive, hydrate on visibility/idle or don't even wrap with lazy at all. You might miss some user interaction.
