### ISSUE TITLE
Support rootMargin on intersectionObserver

### ISSUE THREAD

**Issue by ScriptedAlchemy** [hadeeb/react-lazy-hydrate#13]
Some components can load in a janky fashion if they are hydrated when directly in view. 

Id like to propose the ability to add a rootMargin, allowing a component to hydrate itself before a user is fully viewing it. 

# Use case:  
- carousels where additional computation is required after mounting
- components that use fade-in effects or lazyloading images does not have a smooth experience
- components that use intersection observer themselves

# Reasoning
Would provide a better UX

**Comment by hadeeb** [comment]
This is interesting.

I am not that familiar with intersection observers to think of a possible solution. Interested to know if you have anything cooking up.

Also, I feel it might be a bit difficult to add more configuration to the component in it's current form.

**Comment by ScriptedAlchemy** [comment]
I can open a PR and just hard code a default margin of like 100px if that’s okay.

**Comment by hadeeb** [comment]
Yes, that would be awesome.

**Comment by ScriptedAlchemy** [comment]
PR open, I'm also open to helping you maintain this project if you're interested. It works better than any of the others out there. Might throw a few more PR's your way

**Comment by hadeeb** [comment]
@ScriptedAlchemy I have added you as a collaborator.

**Comment by ScriptedAlchemy** [comment]
@hadeeb i see you merged my PR, can you push the latest to NPM?

**Comment by szepgergo** [comment]
Hello,
Just saw the PR and was wondering... would it be possible to expose the rootMargin as an optional property with the default of '250px' instead of just hardcoding it in the module? Thank you

**Comment by szepgergo** [comment]
I've tried to make it myself. Please note, I'm not very familiar with TS: #29
