### ISSUE TITLE
Issue Intersection Observer not defined

### ISSUE THREAD

**Issue by nacho2487** [hadeeb/react-lazy-hydrate#27]
We have a problem with [this line](https://github.com/hadeeb/react-lazy-hydration/blob/d47e0ebf5cc441c56295d7518c1430e52becfe8a/src/index.tsx#L23) on some browsers that we are crashing with this exception:
`Can't find variable: IntersectionObserver` Safari 14.1 on WebMobile
`IntersectionObserver is not defined` Chrome 49 on Desktop

We can change it to `typeof IntersectionObserver !== 'undefined'` or `window.IntersectionObserver`
Can we make a PR with this change? 
Thanks

**Comment by berndartmueller** [comment]
@hadeeb thanks for fixing this issue! Could you please create a new release? Thanks!
