### ISSUE TITLE
Feature Suggestion - Custom wrapper element

### ISSUE THREAD

**Issue by tomkelsey** [hadeeb/react-lazy-hydrate#38]
Hi,

Great work with this project 👍 

I wondered if it would be possible to include the ability to specify a custom wrapper element?

By default it could be a div (so it isn't a breaking change) but an additional `wrapper` attribute could be available to allow spans, articles, etc?

**Comment by hadeeb** [comment]
You can do that by passing a string to `noWrapper` prop.

https://github.com/hadeeb/react-lazy-hydration/releases/tag/v0.1.0

**Comment by tomkelsey** [comment]
Thanks - I’m not sure if I’m misunderstanding the code but I think as it
is, after hydration, the custom wrapper element is ignored and just the
children are rendered?

Whilst if the default div wrapper is used, the div wrapper is rendered
regardless of hydration status?

For my use case I’m looking to keep the custom wrapper element both before
and after hydration.
